In [19]:
class Employee:
  no_of_employees = 0
  name = ''
  family = ''
  salary = ''
  department = ''
  employees = []
  def __init__(self, name, family, salary, department):
    self.name = name
    self.family = family
    self.salary = salary
    self.department = department
    Employee.no_of_employees += 1
    Employee.employees.append([name, family, salary, department])
  def avg_salary():
    total_sal = sum([employee[2] for employee in Employee.employees])
    return round(total_sal/Employee.no_of_employees,2)

class FulltimeEmployee(Employee):
  pass

#Employee('Nikhila', 'reddy', 340000, 'Data')
#Employee('Tommy', 'Preetham', 75000, 'Development')
#FulltimeEmployee('Vishnupriya', 'Vardhana', 136000, 'Testing')
# print('Average salary of employees:',Employee.avg_salary())

In [20]:
Employee('Nikhila', 'reddy', 340000, 'Data')
Employee('Tommy', 'Preetham', 75000, 'Development')
FulltimeEmployee('Vishnupriya', 'Vardhana', 136000, 'Testing')
print('Average salary of employees:',Employee.avg_salary())

Average salary of employees: 53666.67


In [21]:
import numpy as np
vector = np.random.uniform(1,20,20)
arr = vector.reshape(4,5)
maxn = np.amax(arr, axis=1)
print('Original array:\n',arr)
print('\n\nArray after replacing max with 0:\n',np.where(np.isin(arr,maxn), 0, arr))

Original array:
 [[14.22730078  2.95777732  6.07418225 12.47477073 14.19215044]
 [ 5.26963977  1.16641329  5.24193449 18.50115169 19.70116806]
 [17.41499175  8.91011601  8.52445735 10.53037579 16.10837561]
 [11.25693805 18.56341935  6.18983595 11.2568489   3.88435677]]


Array after replacing max with 0:
 [[ 0.          2.95777732  6.07418225 12.47477073 14.19215044]
 [ 5.26963977  1.16641329  5.24193449 18.50115169  0.        ]
 [ 0.          8.91011601  8.52445735 10.53037579 16.10837561]
 [11.25693805  0.          6.18983595 11.2568489   3.88435677]]
